development:
  adapter: postgresql
  database: palette_pal_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: palette_pal_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: palette_pal_production
  pool: 5
  timeout: 5000